version: '3'

services:
  web:
    build: . 
    command: > 
      bash -c 
      "python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    # expose:
    #   - 5435
    ports:
      - "54323:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=hscdb
      - POSTGRES_HOST=127.0.0.1