# Generated by Django 2.1.4 on 2019-01-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190103_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Okay'), ('C', 'Cancelled'), ('R', 'Rejected')], default='P', max_length=1, null=True),
        ),
    ]
