# Generated by Django 2.1.4 on 2019-01-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_subscriber_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
